#http://blog.toast38coza.me/up-and-running-with-kong-and-docker/
# Try this: https://mhdzaherghaibeh.name/2017/02/02/docker-compose-wait-dont-run-it-now/

version: "2.1"

services:
  kong-database:
    build:
      context: .
    container_name: kong-database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
#    volumes:
#      - "db-data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh"]
      interval: 10s
      timeout: 10s
      retries: 3


  kong:
    image: kong:0.9.9
    container_name: kong
    restart: always
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "7946:7946"
      - "7946:7946/udp"
    depends_on:
      kong-database:
        condition: service_healthy
#
#  ui:
#    image: pgbi/kong-dashboard
#    container_name: kong-dashboard
#    ports:
#      - "8080:8080"
#    links:
#      - kong-database
#      - kong
#

volumes:
  db-data:
