#http://blog.toast38coza.me/up-and-running-with-kong-and-docker/
# Try this: https://mhdzaherghaibeh.name/2017/02/02/docker-compose-wait-dont-run-it-now/

version: "2.1"

services:
  kong-database:
    image: postgres:9.4
    container_name: kong-database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
#    volumes:
#      - "db-data:/var/lib/postgresql/data"


  kong:
    image: kong:0.9.9
    container_name: kong
    restart: always
    environment:
      - WAIT_COMMAND=[ $$(curl --write-out %{http_code} --silent --output /dev/null http://kong-database:5432) = 200 ]
      - WAIT_START_CMD=kong start
      - WAIT_SLEEP=2
      - WAIT_LOOPS=20
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "7946:7946"
      - "7946:7946/udp"
    links:
      - kong-database
    command: sh wait_to_start.sh

#
#  ui:
#    image: pgbi/kong-dashboard
#    container_name: kong-dashboard
#    ports:
#      - "8080:8080"
#    links:
#      - kong-database
#      - kong
#

volumes:
  db-data:
