postgres:
  container_name: postgres
  image: "postgres:9.5"
  ports:
    - 5432:5432
  environment:
    - POSTGRES_PASSWORD=postgres
pgadmin:
  container_name: pgadmin
  image: "fenglc/pgadmin4"
  ports:
    - 5050:5050
